# Generated by Django 3.2.4 on 2021-06-11 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(max_length=50)),
                ('preco', models.CharField(max_length=50)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_produtos')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
