# Generated by Django 3.2.4 on 2021-06-27 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='placa',
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
